source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'classifier-reborn'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    # gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-polyglot'
    # gem 'jekyll-regex-replace'
    # gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-tabs'
    gem 'jekyll-timeago', '~> 0.15.0'
    gem 'jekyll-toc'
    # gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'terser', '~> 1.2', '>= 1.2.4'
    gem 'unicode_utils'
    gem 'webrick', '~> 1.3', '>= 1.3.1'
    gem 'html-proofer'
end
group :other_plugins do
    gem 'css_parser', '~> 1.7'
    gem 'feedjira'
    gem 'httparty'
    gem 'mini_magick'
    # gem 'exif'
    gem 'exiftool'
    gem 'exiftool_vendored'
    # for download-3rd-party.rb (moved to desktop)
    # gem 'digest', '~> 3.0'
    # gem 'fileutils', '~> 1.7', '>= 1.7.3'
    # gem 'open-uri', '~> 0.4.1'
    # gem 'uri', '~> 1.0', '>= 1.0.2'
end
